# Generated by Django 3.2.18 on 2023-03-03 08:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_auto_20230303_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(default=accounts.models.User, max_length=254),
        ),
    ]
