# Generated by Django 3.2.18 on 2023-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0006_auto_20230303_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
