# Generated by Django 3.2.18 on 2023-03-04 10:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0009_alter_tasks_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(default=django.contrib.auth.models.User, max_length=254),
        ),
    ]
