# Generated by Django 3.2.18 on 2023-03-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0012_auto_20230304_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(default='accounts.User', max_length=254),
        ),
    ]
