# Generated by Django 3.2.18 on 2023-03-04 14:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0016_alter_tasks_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(default=accounts.models.User, max_length=254),
        ),
    ]
